-- IT Compass - Script tao 25 bang MySQL (bo bang tieng Viet khong dau)
-- MySQL 8+

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS nguoi_dung (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ho_ten VARCHAR(150) NOT NULL,
  email VARCHAR(191) NOT NULL UNIQUE,
  mat_khau_ma_hoa VARCHAR(255) NOT NULL,
  vai_tro ENUM('hoc_vien','mentor','quan_tri') NOT NULL DEFAULT 'hoc_vien',
  trang_thai ENUM('hoat_dong','tam_khoa','khoa') NOT NULL DEFAULT 'hoat_dong',
  email_xac_thuc_luc DATETIME NULL,
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ho_so_nguoi_dung (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nguoi_dung_id BIGINT UNSIGNED NOT NULL UNIQUE,
  avatar_url VARCHAR(500), anh_bia_url VARCHAR(500), so_dien_thoai VARCHAR(30), dia_diem VARCHAR(120),
  nam_sinh SMALLINT UNSIGNED, gioi_tinh ENUM('nam','nu','khac'),
  tinh_thanh VARCHAR(120), truong_hoc_cong_ty VARCHAR(191), lop_khoa_phong_ban VARCHAR(191),
  gioi_thieu TEXT, github_url VARCHAR(500), linkedin_url VARCHAR(500), chuc_danh VARCHAR(150),
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_hsnd_nd FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ky_nang (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ten VARCHAR(120) NOT NULL UNIQUE,
  slug VARCHAR(150) NOT NULL UNIQUE,
  nhom VARCHAR(100),
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ky_nang_nguoi_dung (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nguoi_dung_id BIGINT UNSIGNED NOT NULL,
  ky_nang_id BIGINT UNSIGNED NOT NULL,
  cap_do ENUM('co_ban','trung_binh','kha','chuyen_gia'),
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_knd (nguoi_dung_id, ky_nang_id),
  CONSTRAINT fk_knd_nd FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_knd_kn FOREIGN KEY (ky_nang_id) REFERENCES ky_nang(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hoc_van (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nguoi_dung_id BIGINT UNSIGNED NOT NULL,
  ten_truong VARCHAR(191) NOT NULL,
  bang_cap VARCHAR(120), chuyen_nganh VARCHAR(120),
  nam_bat_dau SMALLINT UNSIGNED, nam_ket_thuc SMALLINT UNSIGNED,
  gpa DECIMAL(3,2), mo_ta TEXT,
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_hv_nd FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nhom_nghe (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ten VARCHAR(120) NOT NULL UNIQUE,
  slug VARCHAR(150) NOT NULL UNIQUE,
  mo_ta TEXT,
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nghe (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nhom_nghe_id BIGINT UNSIGNED NOT NULL,
  ten VARCHAR(150) NOT NULL UNIQUE,
  slug VARCHAR(170) NOT NULL UNIQUE,
  mo_ta TEXT, luong_tb_min INT UNSIGNED, luong_tb_max INT UNSIGNED, icon VARCHAR(255),
  dang_hoat_dong TINYINT(1) NOT NULL DEFAULT 1,
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_nghe_nhom FOREIGN KEY (nhom_nghe_id) REFERENCES nhom_nghe(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ky_nang_nghe (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nghe_id BIGINT UNSIGNED NOT NULL,
  ky_nang_id BIGINT UNSIGNED NOT NULL,
  thu_tu_uu_tien INT UNSIGNED,
  UNIQUE KEY uq_knng (nghe_id, ky_nang_id),
  CONSTRAINT fk_knng_nghe FOREIGN KEY (nghe_id) REFERENCES nghe(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_knng_kn FOREIGN KEY (ky_nang_id) REFERENCES ky_nang(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bai_test (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tieu_de VARCHAR(191) NOT NULL,
  mo_ta TEXT, phien_ban VARCHAR(30) NOT NULL DEFAULT '1.0',
  dang_hoat_dong TINYINT(1) NOT NULL DEFAULT 1,
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cau_hoi_test (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  bai_test_id BIGINT UNSIGNED NOT NULL,
  noi_dung_cau_hoi TEXT NOT NULL,
  loai_cau_hoi ENUM('chon_mot','chon_nhieu','thang_diem') NOT NULL DEFAULT 'chon_mot',
  thu_tu INT UNSIGNED NOT NULL DEFAULT 0,
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_cht_bt FOREIGN KEY (bai_test_id) REFERENCES bai_test(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lua_chon_test (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  cau_hoi_id BIGINT UNSIGNED NOT NULL,
  noi_dung_lua_chon VARCHAR(300) NOT NULL,
  gia_tri_lua_chon VARCHAR(80),
  thu_tu INT UNSIGNED NOT NULL DEFAULT 0,
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_lct_cht FOREIGN KEY (cau_hoi_id) REFERENCES cau_hoi_test(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lan_lam_test (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nguoi_dung_id BIGINT UNSIGNED NULL,
  bai_test_id BIGINT UNSIGNED NOT NULL,
  bat_dau_luc DATETIME, nop_luc DATETIME,
  trang_thai ENUM('dang_lam','da_nop','da_huy') NOT NULL DEFAULT 'dang_lam',
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_llt_nd FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_llt_bt FOREIGN KEY (bai_test_id) REFERENCES bai_test(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cau_tra_loi_test (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  lan_lam_id BIGINT UNSIGNED NOT NULL,
  cau_hoi_id BIGINT UNSIGNED NOT NULL,
  lua_chon_id BIGINT UNSIGNED NULL,
  gia_tri_tra_loi VARCHAR(120),
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ctl_llt FOREIGN KEY (lan_lam_id) REFERENCES lan_lam_test(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ctl_cht FOREIGN KEY (cau_hoi_id) REFERENCES cau_hoi_test(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ctl_lct FOREIGN KEY (lua_chon_id) REFERENCES lua_chon_test(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ket_qua_test (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  lan_lam_id BIGINT UNSIGNED NOT NULL UNIQUE,
  nguoi_dung_id BIGINT UNSIGNED NULL,
  tom_tat_ket_qua TEXT, loai_tinh_cach VARCHAR(60), nghe_phu_hop_nhat_id BIGINT UNSIGNED NULL,
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_kqt_llt FOREIGN KEY (lan_lam_id) REFERENCES lan_lam_test(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_kqt_nd FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_kqt_nghe FOREIGN KEY (nghe_phu_hop_nhat_id) REFERENCES nghe(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS chi_tiet_ket_qua_test (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ket_qua_id BIGINT UNSIGNED NOT NULL,
  nghe_id BIGINT UNSIGNED NOT NULL,
  diem_phu_hop DECIMAL(5,2) NOT NULL,
  thu_hang INT UNSIGNED,
  UNIQUE KEY uq_ctkqt (ket_qua_id, nghe_id),
  CONSTRAINT fk_ctkqt_kqt FOREIGN KEY (ket_qua_id) REFERENCES ket_qua_test(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ctkqt_nghe FOREIGN KEY (nghe_id) REFERENCES nghe(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mentor (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nguoi_dung_id BIGINT UNSIGNED NULL,
  ten VARCHAR(150) NOT NULL,
  slug VARCHAR(180) NOT NULL UNIQUE,
  avatar_url VARCHAR(500), tieu_de VARCHAR(191), gioi_thieu TEXT,
  trinh_do_mentor ENUM('sinh_vien','fresher','junior','middle','senior','lead','architect','manager'),
  mang_chuyen_mon VARCHAR(100),
  so_nam_kinh_nghiem SMALLINT UNSIGNED, gia_theo_gio INT UNSIGNED,
  truong_hoc_hien_tai VARCHAR(191), cong_ty_hien_tai VARCHAR(191), chuc_danh_hien_tai VARCHAR(191),
  ngon_ngu_tu_van VARCHAR(100),
  so_luong_danh_gia INT UNSIGNED NOT NULL DEFAULT 0,
  da_xac_thuc TINYINT(1) NOT NULL DEFAULT 0,
  trang_thai ENUM('hoat_dong','tam_dung') NOT NULL DEFAULT 'hoat_dong',
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_mentor_nd FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ky_nang_mentor (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  mentor_id BIGINT UNSIGNED NOT NULL,
  ky_nang_id BIGINT UNSIGNED NOT NULL,
  UNIQUE KEY uq_knm (mentor_id, ky_nang_id),
  CONSTRAINT fk_knm_mentor FOREIGN KEY (mentor_id) REFERENCES mentor(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_knm_kn FOREIGN KEY (ky_nang_id) REFERENCES ky_nang(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mentor_da_luu (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nguoi_dung_id BIGINT UNSIGNED NOT NULL,
  mentor_id BIGINT UNSIGNED NOT NULL,
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_mdl (nguoi_dung_id, mentor_id),
  CONSTRAINT fk_mdl_nd FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_mdl_mentor FOREIGN KEY (mentor_id) REFERENCES mentor(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lich_hen_mentor (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nguoi_dung_id BIGINT UNSIGNED NOT NULL,
  mentor_id BIGINT UNSIGNED NOT NULL,
  lich_hen_luc DATETIME NOT NULL,
  thoi_luong_phut INT UNSIGNED NOT NULL,
  gia INT UNSIGNED, ghi_chu TEXT,
  trang_thai ENUM('cho_xac_nhan','da_xac_nhan','hoan_thanh','da_huy') NOT NULL DEFAULT 'cho_xac_nhan',
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_lhm_nd FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_lhm_mentor FOREIGN KEY (mentor_id) REFERENCES mentor(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS danh_muc_blog (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ten VARCHAR(120) NOT NULL UNIQUE,
  slug VARCHAR(150) NOT NULL UNIQUE,
  mo_ta TEXT,
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bai_viet_blog (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tac_gia_id BIGINT UNSIGNED NOT NULL,
  tieu_de VARCHAR(220) NOT NULL,
  slug VARCHAR(240) NOT NULL UNIQUE,
  tom_tat VARCHAR(500) NULL,
  noi_dung TEXT NOT NULL,
  the_loai VARCHAR(100) NULL,
  anh_bia_url VARCHAR(500) NULL,
  thoi_gian_doc VARCHAR(50) NULL,
  noi_bat TINYINT(1) NOT NULL DEFAULT 0,
  meta_tieu_de VARCHAR(220) NULL,
  meta_mo_ta VARCHAR(320) NULL,
  canonical_url VARCHAR(500) NULL,
  og_image_url VARCHAR(500) NULL,
  khong_lap_chi_muc TINYINT(1) NOT NULL DEFAULT 0,
  tu_khoa_seo VARCHAR(500) NULL,
  luot_xem INT UNSIGNED NOT NULL DEFAULT 0,
  luot_thich INT UNSIGNED NOT NULL DEFAULT 0,
  xuat_ban_luc DATETIME NULL,
  len_lich_luc DATETIME NULL,
  xuat_ban_boi BIGINT UNSIGNED NULL,
  xoa_luc DATETIME NULL,
  xoa_boi BIGINT UNSIGNED NULL,
  trang_thai ENUM('nhap','len_lich','xuat_ban') NOT NULL DEFAULT 'xuat_ban',
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_bv_tac_gia_id (tac_gia_id),
  KEY idx_bv_trang_thai_xuat_ban (trang_thai, xuat_ban_luc),
  KEY idx_bv_len_lich_luc (len_lich_luc),
  KEY idx_bv_xoa_luc (xoa_luc),
  CONSTRAINT fk_bv_tac_gia FOREIGN KEY (tac_gia_id) REFERENCES nguoi_dung(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS binh_luan_bai_viet (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  bai_viet_id BIGINT UNSIGNED NOT NULL,
  nguoi_dung_id BIGINT UNSIGNED NULL,
  ten_khach VARCHAR(120) NULL,
  noi_dung TEXT NOT NULL,
  trang_thai ENUM('hien','an') NOT NULL DEFAULT 'hien',
  xoa_luc DATETIME NULL,
  xoa_boi BIGINT UNSIGNED NULL,
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_blbv_bai_viet_trang_thai (bai_viet_id, trang_thai),
  KEY idx_blbv_xoa_luc (xoa_luc),
  CONSTRAINT fk_blbv_bv FOREIGN KEY (bai_viet_id) REFERENCES bai_viet_blog(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_blbv_nd FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS thich_bai_viet (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nguoi_dung_id BIGINT UNSIGNED NOT NULL,
  bai_viet_id BIGINT UNSIGNED NOT NULL,
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_tbv (nguoi_dung_id, bai_viet_id),
  CONSTRAINT fk_tbv_nd FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_tbv_bv FOREIGN KEY (bai_viet_id) REFERENCES bai_viet_blog(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS luu_bai_viet (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nguoi_dung_id BIGINT UNSIGNED NOT NULL,
  bai_viet_id BIGINT UNSIGNED NOT NULL,
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_lbv (nguoi_dung_id, bai_viet_id),
  CONSTRAINT fk_lbv_nd FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_lbv_bv FOREIGN KEY (bai_viet_id) REFERENCES bai_viet_blog(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lien_he (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ho_ten VARCHAR(150) NOT NULL,
  email VARCHAR(191) NOT NULL,
  tieu_de VARCHAR(220), noi_dung TEXT NOT NULL,
  trang_thai ENUM('moi','dang_xu_ly','da_xu_ly','dong') NOT NULL DEFAULT 'moi',
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cau_hinh_he_thong (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  khoa_cau_hinh VARCHAR(191) NOT NULL UNIQUE,
  gia_tri_cau_hinh LONGTEXT,
  mo_ta TEXT,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cuoc_tro_chuyen (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nguoi_dung_id BIGINT UNSIGNED NOT NULL,
  mentor_id BIGINT UNSIGNED NOT NULL,
  trang_thai ENUM('dang_mo','da_dong') NOT NULL DEFAULT 'dang_mo',
  tao_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cap_nhat_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_cuoc_tro_chuyen_1_1 (nguoi_dung_id, mentor_id),
  KEY idx_ctc_mentor_id (mentor_id),
  CONSTRAINT fk_ctc_nguoi_dung FOREIGN KEY (nguoi_dung_id) REFERENCES nguoi_dung(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ctc_mentor FOREIGN KEY (mentor_id) REFERENCES mentor(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tin_nhan (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  cuoc_tro_chuyen_id BIGINT UNSIGNED NOT NULL,
  nguoi_gui_id BIGINT UNSIGNED NOT NULL,
  noi_dung TEXT NULL,
  loai_tin_nhan ENUM('van_ban','hinh_anh','tep') NOT NULL DEFAULT 'van_ban',
  tep_dinh_kem_url VARCHAR(500) NULL,
  da_xem TINYINT(1) NOT NULL DEFAULT 0,
  gui_luc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_tin_nhan_cuoc_tro_chuyen_id (cuoc_tro_chuyen_id),
  KEY idx_tin_nhan_nguoi_gui_id (nguoi_gui_id),
  KEY idx_tin_nhan_gui_luc (gui_luc),
  CONSTRAINT fk_tin_nhan_cuoc_tro_chuyen FOREIGN KEY (cuoc_tro_chuyen_id) REFERENCES cuoc_tro_chuyen(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_tin_nhan_nguoi_gui FOREIGN KEY (nguoi_gui_id) REFERENCES nguoi_dung(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
