import { Brain, Code2, Database, Layout, Shield, Blocks, Server, Gamepad2 } from 'lucide-react';

export const MAJORS_DB = {
    'ky-thuat-phan-mem': {
        slug: 'ky-thuat-phan-mem',
        title: 'Kỹ thuật phần mềm',
        icon: Code2,
        iconBg: 'bg-blue-500/10 border border-blue-500/20',
        iconColor: 'text-blue-600',
        headline: 'Xây dựng cốt lõi của thế giới số',
        description: 'Tập trung vào quy trình thiết kế, phát triển và bảo trì phần mềm và ứng dụng ở quy mô lớn.',
        overview: 'Kỹ thuật phần mềm (Software Engineering) là trái tim của ngành CNTT. Hệ thống không chỉ dừng ở việc "biết code" mà còn áp dụng nguyên lý toán học, kỹ thuật phần cứng và quy trình để thiết kế, phát triển toàn bộ hệ thống phần mềm nhằm giải quyết vấn đề với quy mô hàng triệu người dùng.',
        careers: ['Lập trình viên Frontend / Backend', 'Kỹ sư Fullstack', 'Kiến trúc sư phần mềm (Solutions Architect)', 'Kỹ sư kiểm thử tự động (Automation QA)'],
        skills: ['Cấu trúc dữ liệu & Giải thuật', 'OOP & Design Patterns', 'Git & CI/CD cơ bản', 'Tư duy logic và giải quyết vấn đề'],
        holland: ['Nghiên cứu (Investigative)', 'Kỹ thuật (Realistic)'],
        tags: ['Web', 'Mobile', 'System Design', 'Algorithms'],
    },
    'tri-tue-nhan-tao': {
        slug: 'tri-tue-nhan-tao',
        title: 'Trí tuệ nhân tạo (AI)',
        icon: Brain,
        iconBg: 'bg-emerald-500/10 border border-emerald-500/20',
        iconColor: 'text-emerald-600',
        headline: 'Dạy máy móc cách học và suy nghĩ',
        description: 'Nghiên cứu về Machine Learning, Deep Learning, và Xử lý ngôn ngữ tự nhiên để tạo ra các hệ thống thông minh.',
        overview: 'Trí tuệ nhân tạo đang thay đổi cách thế giới vận hành. Ngành này tập trung vào việc mô phỏng quá trình nhận thức của con người bằng máy móc thông qua các mô hình Machine Learning, Computer Vision và xử lý ngôn ngữ tự nhiên (NLP).',
        careers: ['Kỹ sư AI/Machine Learning', 'Nhà nghiên cứu AI (AI Researcher)', 'Kỹ sư Computer Vision', 'Kỹ sư NLP (Xử lý ngôn ngữ tự nhiên)'],
        skills: ['Toán đại số tuyến tính & Xác suất', 'Python (TensorFlow, PyTorch)', 'Xử lý dữ liệu lớn', 'Khả năng nghiên cứu học thuật'],
        holland: ['Nghiên cứu (Investigative)', 'Nghệ thuật (Artistic) - Sự sáng tạo thuật toán'],
        tags: ['Machine Learning', 'Python', 'NLP', 'Computer Vision'],
    },
    'khoa-hoc-du-lieu': {
        slug: 'khoa-hoc-du-lieu',
        title: 'Khoa học dữ liệu',
        icon: Database,
        iconBg: 'bg-fuchsia-500/10 border border-fuchsia-500/20',
        iconColor: 'text-fuchsia-600',
        headline: 'Khai phá giá trị từ những con số',
        description: 'Sử dụng các phương pháp thống kê và phân tích để tìm ra xu hướng và đưa ra quyết định kinh doanh từ dữ liệu.',
        overview: 'Dữ liệu là nguồn dầu mỏ mới. Khoa học dữ liệu khai thác và tinh tinh chế lượng dữ liệu khổng lồ thành Insight kinh doanh. Bạn sẽ học cách thu thập, làm sạch, và trực quan hóa dữ liệu để dự đoán các xu hướng trong tương lai.',
        careers: ['Chuyên viên Phân tích Dữ liệu (Data Analyst)', 'Kỹ sư Dữ liệu (Data Engineer)', 'Chuyên gia Khoa học Dữ liệu (Data Scientist)'],
        skills: ['SQL & NoSQL', 'Thống kê ứng dụng', 'Data Visualization (Tableau, PowerBI)', 'Khai phá dữ liệu (Data Mining)'],
        holland: ['Nghiên cứu (Investigative)', 'Nghiệp vụ (Conventional)'],
        tags: ['Data Analysis', 'SQL', 'Statistics', 'Big Data'],
    },
    'an-toan-thong-tin': {
        slug: 'an-toan-thong-tin',
        title: 'An toàn thông tin',
        icon: Shield,
        iconBg: 'bg-rose-500/10 border border-rose-500/20',
        iconColor: 'text-rose-600',
        headline: 'Bảo vệ hệ thống khỏi các mối đe dọa',
        description: 'Ngành học rèn luyện kỹ năng phát hiện lỗ hổng, bảo vệ dữ liệu và ứng phó với các cuộc tấn công mạng.',
        overview: 'An toàn thông tin đóng vai trò phòng thủ và tấn công (Red team/Blue team) trong không gian mạng. Bạn sẽ đóng vai hacker mũ trắng tìm cách phá vỡ rào chắn để bảo vệ các tổ chức khỏi bị đánh cắp dữ liệu và tấn công mã độc.',
        careers: ['Chuyên gia bảo mật (Security Analyst)', 'Kỹ sư kiểm thử xâm nhập (Pentester)', 'Kiến trúc sư an toàn mạng', 'Chuyên viên ứng phó sự cố'],
        skills: ['Mạng máy tính & Giao thức', 'Mật mã học (Cryptography)', 'Linux & Bash Scripting', 'Tìm kiếm & khai thác lỗ hổng (Exploit)'],
        holland: ['Nghiên cứu (Investigative)', 'Kỹ thuật (Realistic)'],
        tags: ['Cybersecurity', 'Pentest', 'Cryptography', 'Network'],
    },
    'thiet-ke-ui-ux': {
        slug: 'thiet-ke-ui-ux',
        title: 'Thiết kế UI/UX',
        icon: Layout,
        iconBg: 'bg-amber-500/10 border border-amber-500/20',
        iconColor: 'text-amber-600',
        headline: 'Sự giao thoa giữa nghệ thuật và logic',
        description: 'Nghiên cứu hành vi người dùng, thiết kế giao diện giúp phần mềm trở nên trực quan, dễ dùng và cuốn hút hơn.',
        overview: 'Không chỉ là vẽ làm sao cho đẹp. Thiết kế UI/UX là quá trình thấu cảm tâm lý người dùng, xây dựng hành trình trải nghiệm (User Flow), và tạo ra các bộ quy chuẩn thiết kế (Design System) để phần mềm dễ sử dụng và tối ưu chuyển đổi.',
        careers: ['UX Researcher', 'Nhà thiết kế UI/UX', 'Product Designer', 'Interaction Designer (Thiết kế tương tác)'],
        skills: ['Figma / Sketch', 'Nghiên cứu người dùng (User Research)', 'Thiết kế nguyên mẫu (Prototyping)', 'Wireframing & Usability Testing'],
        holland: ['Nghệ thuật (Artistic)', 'Xã hội (Social)'],
        tags: ['Figma', 'Prototyping', 'User Research', 'Design System'],
    },
    'phan-tich-nghiep-vu': {
        slug: 'phan-tich-nghiep-vu',
        title: 'Phân tích nghiệp vụ (BA)',
        icon: Blocks,
        iconBg: 'bg-indigo-500/10 border border-indigo-500/20',
        iconColor: 'text-indigo-600',
        headline: 'Cầu nối giữa kỹ thuật và doanh nghiệp',
        description: 'Phân tích yêu cầu kinh doanh và chuyển hóa thành các giải pháp công nghệ đáp ứng mục tiêu của doanh nghiệp.',
        overview: 'BA đóng vai trò chuyển dịch nhu cầu kinh doanh bằng ngôn ngữ con người sang ngôn ngữ kỹ thuật cho đội ngũ lập trình. Bạn sẽ khảo sát, phân tích, tài liệu hóa và viết các quy trình (BPMN) để đảm bảo sản phẩm ra đời đúng với mong đợi kinh doanh.',
        careers: ['Phân tích nghiệp vụ IT (IT Business Analyst)', 'Product Owner', 'Kỹ sư yêu cầu (Requirements Engineer)'],
        skills: ['Kỹ năng giao tiếp & Đàm phán', 'Tài liệu hóa (UML, user stories)', 'Hiểu biết quy trình Agile/Scrum', 'Tư duy hệ thống'],
        holland: ['Quản lý/Khởi nghiệp (Enterprising)', 'Xã hội (Social)'],
        tags: ['Requirements', 'UML', 'Communication', 'Agile'],
    },
    'cloud-devops': {
        slug: 'cloud-devops',
        title: 'Cloud & DevOps',
        icon: Server,
        iconBg: 'bg-cyan-500/10 border border-cyan-500/20',
        iconColor: 'text-cyan-600',
        headline: 'Vận hành hạ tầng công nghệ hiện đại',
        description: 'Quản trị hệ thống máy chủ đám mây, tự động hóa quy trình triển khai và đảm bảo hệ thống luôn sẵn sàng 24/7.',
        overview: 'DevOps (Development & Operations) là văn hóa kết nối đội code và đội vận hành. Bạn sẽ thiết lập đường ống tích hợp liên tục (CI/CD) tự động, và cung ứng các dịch vụ Cloud như AWS/Azure để đảm bảo hệ thống chạy ổn định và chịu tải cao.',
        careers: ['Kỹ sư DevOps', 'Kiến trúc sư Đám mây (Cloud Architect)', 'Site Reliability Engineer (SRE)', 'Kỹ sư Hệ thống (SysAdmin)'],
        skills: ['Tự động hóa (CI/CD Pipeline)', 'Docker & Kubernetes', 'Mạng Đám mây (AWS, GCP)', 'Viết script (Bash, Python, Terraform)'],
        holland: ['Kỹ thuật (Realistic)', 'Nghiệp vụ (Conventional)'],
        tags: ['AWS', 'Docker', 'CI/CD', 'Kubernetes'],
    },
    'phat-trien-game': {
        slug: 'phat-trien-game',
        title: 'Phát triển Game',
        icon: Gamepad2,
        iconBg: 'bg-violet-500/10 border border-violet-500/20',
        iconColor: 'text-violet-600',
        headline: 'Sáng tạo thế giới tương tác ảo',
        description: 'Kết hợp lập trình, đồ họa 3D, vật lý và kịch bản để tạo ra các trò chơi giải trí trên nhiều nền tảng.',
        overview: 'Ngành học đan xen kiến thức đồ họa máy tính, vật lý, AI và storytelling. Tạo ra game không chỉ cần biết code mà còn cần khả năng sắp xếp Engine (Unity/Unreal), xử lý logic toán học (vector, matrix) trong không gian 3 chiều.',
        careers: ['Lập trình viên Game (Game Developer)', 'Thiết kế hệ thống Game (Game Designer)', 'Technical Artist', 'Chuyên viên xử lý vật lý game'],
        skills: ['C++ hoặc C#', 'Sử dụng Game Engine (Unity, Unreal)', 'Kiến thức về tối ưu hiệu suất render', 'Storytelling & Game mechanics'],
        holland: ['Nghệ thuật (Artistic)', 'Nghiên cứu (Investigative)'],
        tags: ['Unity', 'Unreal Engine', 'C++', 'Creative'],
    },
};

export const MAJORS_LIST = Object.values(MAJORS_DB);
